//go:build !ignore_autogenerated

/*
Copyright 2026 Dmitry Lebedev.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/crossplane/crossplane-runtime/apis/common/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerRegistry) DeepCopyInto(out *ContainerRegistry) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerRegistry.
func (in *ContainerRegistry) DeepCopy() *ContainerRegistry {
	if in == nil {
		return nil
	}
	out := new(ContainerRegistry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ContainerRegistry) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerRegistryConfiguration) DeepCopyInto(out *ContainerRegistryConfiguration) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerRegistryConfiguration.
func (in *ContainerRegistryConfiguration) DeepCopy() *ContainerRegistryConfiguration {
	if in == nil {
		return nil
	}
	out := new(ContainerRegistryConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerRegistryDiskStats) DeepCopyInto(out *ContainerRegistryDiskStats) {
	*out = *in
	if in.SizeGB != nil {
		in, out := &in.SizeGB, &out.SizeGB
		*out = new(int)
		**out = **in
	}
	if in.UsedGB != nil {
		in, out := &in.UsedGB, &out.UsedGB
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerRegistryDiskStats.
func (in *ContainerRegistryDiskStats) DeepCopy() *ContainerRegistryDiskStats {
	if in == nil {
		return nil
	}
	out := new(ContainerRegistryDiskStats)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerRegistryList) DeepCopyInto(out *ContainerRegistryList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ContainerRegistry, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerRegistryList.
func (in *ContainerRegistryList) DeepCopy() *ContainerRegistryList {
	if in == nil {
		return nil
	}
	out := new(ContainerRegistryList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ContainerRegistryList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerRegistryObservation) DeepCopyInto(out *ContainerRegistryObservation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(int)
		**out = **in
	}
	if in.PresetID != nil {
		in, out := &in.PresetID, &out.PresetID
		*out = new(int)
		**out = **in
	}
	if in.ConfiguratorID != nil {
		in, out := &in.ConfiguratorID, &out.ConfiguratorID
		*out = new(int)
		**out = **in
	}
	if in.ProjectID != nil {
		in, out := &in.ProjectID, &out.ProjectID
		*out = new(int)
		**out = **in
	}
	if in.DiskStats != nil {
		in, out := &in.DiskStats, &out.DiskStats
		*out = new(ContainerRegistryDiskStats)
		(*in).DeepCopyInto(*out)
	}
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = new(string)
		**out = **in
	}
	if in.UpdatedAt != nil {
		in, out := &in.UpdatedAt, &out.UpdatedAt
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerRegistryObservation.
func (in *ContainerRegistryObservation) DeepCopy() *ContainerRegistryObservation {
	if in == nil {
		return nil
	}
	out := new(ContainerRegistryObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerRegistryParameters) DeepCopyInto(out *ContainerRegistryParameters) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.PresetRef != nil {
		in, out := &in.PresetRef, &out.PresetRef
		*out = new(ContainerRegistryPresetRef)
		**out = **in
	}
	if in.Configuration != nil {
		in, out := &in.Configuration, &out.Configuration
		*out = new(ContainerRegistryConfiguration)
		**out = **in
	}
	if in.ProjectID != nil {
		in, out := &in.ProjectID, &out.ProjectID
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerRegistryParameters.
func (in *ContainerRegistryParameters) DeepCopy() *ContainerRegistryParameters {
	if in == nil {
		return nil
	}
	out := new(ContainerRegistryParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerRegistryPreset) DeepCopyInto(out *ContainerRegistryPreset) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerRegistryPreset.
func (in *ContainerRegistryPreset) DeepCopy() *ContainerRegistryPreset {
	if in == nil {
		return nil
	}
	out := new(ContainerRegistryPreset)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ContainerRegistryPreset) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerRegistryPresetList) DeepCopyInto(out *ContainerRegistryPresetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ContainerRegistryPreset, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerRegistryPresetList.
func (in *ContainerRegistryPresetList) DeepCopy() *ContainerRegistryPresetList {
	if in == nil {
		return nil
	}
	out := new(ContainerRegistryPresetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ContainerRegistryPresetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerRegistryPresetObservation) DeepCopyInto(out *ContainerRegistryPresetObservation) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.DescriptionShort != nil {
		in, out := &in.DescriptionShort, &out.DescriptionShort
		*out = new(string)
		**out = **in
	}
	if in.DiskGB != nil {
		in, out := &in.DiskGB, &out.DiskGB
		*out = new(int)
		**out = **in
	}
	if in.Location != nil {
		in, out := &in.Location, &out.Location
		*out = new(string)
		**out = **in
	}
	if in.Prices != nil {
		in, out := &in.Prices, &out.Prices
		*out = make([]ContainerRegistryPresetPrice, len(*in))
		copy(*out, *in)
	}
	if in.LastObservedAt != nil {
		in, out := &in.LastObservedAt, &out.LastObservedAt
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerRegistryPresetObservation.
func (in *ContainerRegistryPresetObservation) DeepCopy() *ContainerRegistryPresetObservation {
	if in == nil {
		return nil
	}
	out := new(ContainerRegistryPresetObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerRegistryPresetPrice) DeepCopyInto(out *ContainerRegistryPresetPrice) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerRegistryPresetPrice.
func (in *ContainerRegistryPresetPrice) DeepCopy() *ContainerRegistryPresetPrice {
	if in == nil {
		return nil
	}
	out := new(ContainerRegistryPresetPrice)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerRegistryPresetRef) DeepCopyInto(out *ContainerRegistryPresetRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerRegistryPresetRef.
func (in *ContainerRegistryPresetRef) DeepCopy() *ContainerRegistryPresetRef {
	if in == nil {
		return nil
	}
	out := new(ContainerRegistryPresetRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerRegistryPresetSpec) DeepCopyInto(out *ContainerRegistryPresetSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerRegistryPresetSpec.
func (in *ContainerRegistryPresetSpec) DeepCopy() *ContainerRegistryPresetSpec {
	if in == nil {
		return nil
	}
	out := new(ContainerRegistryPresetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerRegistryPresetStatus) DeepCopyInto(out *ContainerRegistryPresetStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerRegistryPresetStatus.
func (in *ContainerRegistryPresetStatus) DeepCopy() *ContainerRegistryPresetStatus {
	if in == nil {
		return nil
	}
	out := new(ContainerRegistryPresetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerRegistryRef) DeepCopyInto(out *ContainerRegistryRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerRegistryRef.
func (in *ContainerRegistryRef) DeepCopy() *ContainerRegistryRef {
	if in == nil {
		return nil
	}
	out := new(ContainerRegistryRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerRegistryRepository) DeepCopyInto(out *ContainerRegistryRepository) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerRegistryRepository.
func (in *ContainerRegistryRepository) DeepCopy() *ContainerRegistryRepository {
	if in == nil {
		return nil
	}
	out := new(ContainerRegistryRepository)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ContainerRegistryRepository) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerRegistryRepositoryList) DeepCopyInto(out *ContainerRegistryRepositoryList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ContainerRegistryRepository, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerRegistryRepositoryList.
func (in *ContainerRegistryRepositoryList) DeepCopy() *ContainerRegistryRepositoryList {
	if in == nil {
		return nil
	}
	out := new(ContainerRegistryRepositoryList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ContainerRegistryRepositoryList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerRegistryRepositoryObservation) DeepCopyInto(out *ContainerRegistryRepositoryObservation) {
	*out = *in
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]ContainerRegistryRepositoryTag, len(*in))
		copy(*out, *in)
	}
	if in.TagCount != nil {
		in, out := &in.TagCount, &out.TagCount
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerRegistryRepositoryObservation.
func (in *ContainerRegistryRepositoryObservation) DeepCopy() *ContainerRegistryRepositoryObservation {
	if in == nil {
		return nil
	}
	out := new(ContainerRegistryRepositoryObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerRegistryRepositoryParameters) DeepCopyInto(out *ContainerRegistryRepositoryParameters) {
	*out = *in
	out.RegistryRef = in.RegistryRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerRegistryRepositoryParameters.
func (in *ContainerRegistryRepositoryParameters) DeepCopy() *ContainerRegistryRepositoryParameters {
	if in == nil {
		return nil
	}
	out := new(ContainerRegistryRepositoryParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerRegistryRepositorySpec) DeepCopyInto(out *ContainerRegistryRepositorySpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	out.ForProvider = in.ForProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerRegistryRepositorySpec.
func (in *ContainerRegistryRepositorySpec) DeepCopy() *ContainerRegistryRepositorySpec {
	if in == nil {
		return nil
	}
	out := new(ContainerRegistryRepositorySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerRegistryRepositoryStatus) DeepCopyInto(out *ContainerRegistryRepositoryStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerRegistryRepositoryStatus.
func (in *ContainerRegistryRepositoryStatus) DeepCopy() *ContainerRegistryRepositoryStatus {
	if in == nil {
		return nil
	}
	out := new(ContainerRegistryRepositoryStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerRegistryRepositoryTag) DeepCopyInto(out *ContainerRegistryRepositoryTag) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerRegistryRepositoryTag.
func (in *ContainerRegistryRepositoryTag) DeepCopy() *ContainerRegistryRepositoryTag {
	if in == nil {
		return nil
	}
	out := new(ContainerRegistryRepositoryTag)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerRegistrySpec) DeepCopyInto(out *ContainerRegistrySpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerRegistrySpec.
func (in *ContainerRegistrySpec) DeepCopy() *ContainerRegistrySpec {
	if in == nil {
		return nil
	}
	out := new(ContainerRegistrySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerRegistryStatus) DeepCopyInto(out *ContainerRegistryStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerRegistryStatus.
func (in *ContainerRegistryStatus) DeepCopy() *ContainerRegistryStatus {
	if in == nil {
		return nil
	}
	out := new(ContainerRegistryStatus)
	in.DeepCopyInto(out)
	return out
}
