// Code generated by counterfeiter. DO NOT EDIT.
package rgwiamfakes

import (
	"context"
	"sync"

	"github.com/lebedevdsl/crossplane-provider-timeweb/internal/clients/rgwiam"
)

type FakeClient struct {
	DeleteUserPolicyStub        func(context.Context, string, string) error
	deleteUserPolicyMutex       sync.RWMutex
	deleteUserPolicyArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}
	deleteUserPolicyReturns struct {
		result1 error
	}
	deleteUserPolicyReturnsOnCall map[int]struct {
		result1 error
	}
	GetUserPolicyStub        func(context.Context, string, string) (string, error)
	getUserPolicyMutex       sync.RWMutex
	getUserPolicyArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}
	getUserPolicyReturns struct {
		result1 string
		result2 error
	}
	getUserPolicyReturnsOnCall map[int]struct {
		result1 string
		result2 error
	}
	ListUserPoliciesStub        func(context.Context, string) ([]string, error)
	listUserPoliciesMutex       sync.RWMutex
	listUserPoliciesArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	listUserPoliciesReturns struct {
		result1 []string
		result2 error
	}
	listUserPoliciesReturnsOnCall map[int]struct {
		result1 []string
		result2 error
	}
	PutUserPolicyStub        func(context.Context, string, string, string) error
	putUserPolicyMutex       sync.RWMutex
	putUserPolicyArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 string
	}
	putUserPolicyReturns struct {
		result1 error
	}
	putUserPolicyReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeClient) DeleteUserPolicy(arg1 context.Context, arg2 string, arg3 string) error {
	fake.deleteUserPolicyMutex.Lock()
	ret, specificReturn := fake.deleteUserPolicyReturnsOnCall[len(fake.deleteUserPolicyArgsForCall)]
	fake.deleteUserPolicyArgsForCall = append(fake.deleteUserPolicyArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}{arg1, arg2, arg3})
	stub := fake.DeleteUserPolicyStub
	fakeReturns := fake.deleteUserPolicyReturns
	fake.recordInvocation("DeleteUserPolicy", []interface{}{arg1, arg2, arg3})
	fake.deleteUserPolicyMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeClient) DeleteUserPolicyCallCount() int {
	fake.deleteUserPolicyMutex.RLock()
	defer fake.deleteUserPolicyMutex.RUnlock()
	return len(fake.deleteUserPolicyArgsForCall)
}

func (fake *FakeClient) DeleteUserPolicyCalls(stub func(context.Context, string, string) error) {
	fake.deleteUserPolicyMutex.Lock()
	defer fake.deleteUserPolicyMutex.Unlock()
	fake.DeleteUserPolicyStub = stub
}

func (fake *FakeClient) DeleteUserPolicyArgsForCall(i int) (context.Context, string, string) {
	fake.deleteUserPolicyMutex.RLock()
	defer fake.deleteUserPolicyMutex.RUnlock()
	argsForCall := fake.deleteUserPolicyArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeClient) DeleteUserPolicyReturns(result1 error) {
	fake.deleteUserPolicyMutex.Lock()
	defer fake.deleteUserPolicyMutex.Unlock()
	fake.DeleteUserPolicyStub = nil
	fake.deleteUserPolicyReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeClient) DeleteUserPolicyReturnsOnCall(i int, result1 error) {
	fake.deleteUserPolicyMutex.Lock()
	defer fake.deleteUserPolicyMutex.Unlock()
	fake.DeleteUserPolicyStub = nil
	if fake.deleteUserPolicyReturnsOnCall == nil {
		fake.deleteUserPolicyReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.deleteUserPolicyReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeClient) GetUserPolicy(arg1 context.Context, arg2 string, arg3 string) (string, error) {
	fake.getUserPolicyMutex.Lock()
	ret, specificReturn := fake.getUserPolicyReturnsOnCall[len(fake.getUserPolicyArgsForCall)]
	fake.getUserPolicyArgsForCall = append(fake.getUserPolicyArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}{arg1, arg2, arg3})
	stub := fake.GetUserPolicyStub
	fakeReturns := fake.getUserPolicyReturns
	fake.recordInvocation("GetUserPolicy", []interface{}{arg1, arg2, arg3})
	fake.getUserPolicyMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeClient) GetUserPolicyCallCount() int {
	fake.getUserPolicyMutex.RLock()
	defer fake.getUserPolicyMutex.RUnlock()
	return len(fake.getUserPolicyArgsForCall)
}

func (fake *FakeClient) GetUserPolicyCalls(stub func(context.Context, string, string) (string, error)) {
	fake.getUserPolicyMutex.Lock()
	defer fake.getUserPolicyMutex.Unlock()
	fake.GetUserPolicyStub = stub
}

func (fake *FakeClient) GetUserPolicyArgsForCall(i int) (context.Context, string, string) {
	fake.getUserPolicyMutex.RLock()
	defer fake.getUserPolicyMutex.RUnlock()
	argsForCall := fake.getUserPolicyArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeClient) GetUserPolicyReturns(result1 string, result2 error) {
	fake.getUserPolicyMutex.Lock()
	defer fake.getUserPolicyMutex.Unlock()
	fake.GetUserPolicyStub = nil
	fake.getUserPolicyReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeClient) GetUserPolicyReturnsOnCall(i int, result1 string, result2 error) {
	fake.getUserPolicyMutex.Lock()
	defer fake.getUserPolicyMutex.Unlock()
	fake.GetUserPolicyStub = nil
	if fake.getUserPolicyReturnsOnCall == nil {
		fake.getUserPolicyReturnsOnCall = make(map[int]struct {
			result1 string
			result2 error
		})
	}
	fake.getUserPolicyReturnsOnCall[i] = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeClient) ListUserPolicies(arg1 context.Context, arg2 string) ([]string, error) {
	fake.listUserPoliciesMutex.Lock()
	ret, specificReturn := fake.listUserPoliciesReturnsOnCall[len(fake.listUserPoliciesArgsForCall)]
	fake.listUserPoliciesArgsForCall = append(fake.listUserPoliciesArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.ListUserPoliciesStub
	fakeReturns := fake.listUserPoliciesReturns
	fake.recordInvocation("ListUserPolicies", []interface{}{arg1, arg2})
	fake.listUserPoliciesMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeClient) ListUserPoliciesCallCount() int {
	fake.listUserPoliciesMutex.RLock()
	defer fake.listUserPoliciesMutex.RUnlock()
	return len(fake.listUserPoliciesArgsForCall)
}

func (fake *FakeClient) ListUserPoliciesCalls(stub func(context.Context, string) ([]string, error)) {
	fake.listUserPoliciesMutex.Lock()
	defer fake.listUserPoliciesMutex.Unlock()
	fake.ListUserPoliciesStub = stub
}

func (fake *FakeClient) ListUserPoliciesArgsForCall(i int) (context.Context, string) {
	fake.listUserPoliciesMutex.RLock()
	defer fake.listUserPoliciesMutex.RUnlock()
	argsForCall := fake.listUserPoliciesArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeClient) ListUserPoliciesReturns(result1 []string, result2 error) {
	fake.listUserPoliciesMutex.Lock()
	defer fake.listUserPoliciesMutex.Unlock()
	fake.ListUserPoliciesStub = nil
	fake.listUserPoliciesReturns = struct {
		result1 []string
		result2 error
	}{result1, result2}
}

func (fake *FakeClient) ListUserPoliciesReturnsOnCall(i int, result1 []string, result2 error) {
	fake.listUserPoliciesMutex.Lock()
	defer fake.listUserPoliciesMutex.Unlock()
	fake.ListUserPoliciesStub = nil
	if fake.listUserPoliciesReturnsOnCall == nil {
		fake.listUserPoliciesReturnsOnCall = make(map[int]struct {
			result1 []string
			result2 error
		})
	}
	fake.listUserPoliciesReturnsOnCall[i] = struct {
		result1 []string
		result2 error
	}{result1, result2}
}

func (fake *FakeClient) PutUserPolicy(arg1 context.Context, arg2 string, arg3 string, arg4 string) error {
	fake.putUserPolicyMutex.Lock()
	ret, specificReturn := fake.putUserPolicyReturnsOnCall[len(fake.putUserPolicyArgsForCall)]
	fake.putUserPolicyArgsForCall = append(fake.putUserPolicyArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 string
	}{arg1, arg2, arg3, arg4})
	stub := fake.PutUserPolicyStub
	fakeReturns := fake.putUserPolicyReturns
	fake.recordInvocation("PutUserPolicy", []interface{}{arg1, arg2, arg3, arg4})
	fake.putUserPolicyMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeClient) PutUserPolicyCallCount() int {
	fake.putUserPolicyMutex.RLock()
	defer fake.putUserPolicyMutex.RUnlock()
	return len(fake.putUserPolicyArgsForCall)
}

func (fake *FakeClient) PutUserPolicyCalls(stub func(context.Context, string, string, string) error) {
	fake.putUserPolicyMutex.Lock()
	defer fake.putUserPolicyMutex.Unlock()
	fake.PutUserPolicyStub = stub
}

func (fake *FakeClient) PutUserPolicyArgsForCall(i int) (context.Context, string, string, string) {
	fake.putUserPolicyMutex.RLock()
	defer fake.putUserPolicyMutex.RUnlock()
	argsForCall := fake.putUserPolicyArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *FakeClient) PutUserPolicyReturns(result1 error) {
	fake.putUserPolicyMutex.Lock()
	defer fake.putUserPolicyMutex.Unlock()
	fake.PutUserPolicyStub = nil
	fake.putUserPolicyReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeClient) PutUserPolicyReturnsOnCall(i int, result1 error) {
	fake.putUserPolicyMutex.Lock()
	defer fake.putUserPolicyMutex.Unlock()
	fake.PutUserPolicyStub = nil
	if fake.putUserPolicyReturnsOnCall == nil {
		fake.putUserPolicyReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.putUserPolicyReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeClient) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.deleteUserPolicyMutex.RLock()
	defer fake.deleteUserPolicyMutex.RUnlock()
	fake.getUserPolicyMutex.RLock()
	defer fake.getUserPolicyMutex.RUnlock()
	fake.listUserPoliciesMutex.RLock()
	defer fake.listUserPoliciesMutex.RUnlock()
	fake.putUserPolicyMutex.RLock()
	defer fake.putUserPolicyMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeClient) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ rgwiam.Client = new(FakeClient)
