//go:build !ignore_autogenerated

/*
Copyright 2026 Dmitry Lebedev.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Cdn) DeepCopyInto(out *Cdn) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Cdn.
func (in *Cdn) DeepCopy() *Cdn {
	if in == nil {
		return nil
	}
	out := new(Cdn)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Cdn) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CdnBucketRef) DeepCopyInto(out *CdnBucketRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CdnBucketRef.
func (in *CdnBucketRef) DeepCopy() *CdnBucketRef {
	if in == nil {
		return nil
	}
	out := new(CdnBucketRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CdnCache) DeepCopyInto(out *CdnCache) {
	*out = *in
	if in.EdgeTTLSeconds != nil {
		in, out := &in.EdgeTTLSeconds, &out.EdgeTTLSeconds
		*out = new(int64)
		**out = **in
	}
	if in.BrowserTTLSeconds != nil {
		in, out := &in.BrowserTTLSeconds, &out.BrowserTTLSeconds
		*out = new(int64)
		**out = **in
	}
	if in.AlwaysOnline != nil {
		in, out := &in.AlwaysOnline, &out.AlwaysOnline
		*out = new(bool)
		**out = **in
	}
	if in.QueryStringCacheKeyMode != nil {
		in, out := &in.QueryStringCacheKeyMode, &out.QueryStringCacheKeyMode
		*out = new(string)
		**out = **in
	}
	if in.QueryStringCacheKeyParams != nil {
		in, out := &in.QueryStringCacheKeyParams, &out.QueryStringCacheKeyParams
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CdnCache.
func (in *CdnCache) DeepCopy() *CdnCache {
	if in == nil {
		return nil
	}
	out := new(CdnCache)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CdnCertificateStatus) DeepCopyInto(out *CdnCertificateStatus) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(int64)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
	if in.CN != nil {
		in, out := &in.CN, &out.CN
		*out = new(string)
		**out = **in
	}
	if in.Domains != nil {
		in, out := &in.Domains, &out.Domains
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.IssuedAt != nil {
		in, out := &in.IssuedAt, &out.IssuedAt
		*out = new(string)
		**out = **in
	}
	if in.ExpiresAt != nil {
		in, out := &in.ExpiresAt, &out.ExpiresAt
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CdnCertificateStatus.
func (in *CdnCertificateStatus) DeepCopy() *CdnCertificateStatus {
	if in == nil {
		return nil
	}
	out := new(CdnCertificateStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CdnCors) DeepCopyInto(out *CdnCors) {
	*out = *in
	if in.Origins != nil {
		in, out := &in.Origins, &out.Origins
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AlwaysAddHeader != nil {
		in, out := &in.AlwaysAddHeader, &out.AlwaysAddHeader
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CdnCors.
func (in *CdnCors) DeepCopy() *CdnCors {
	if in == nil {
		return nil
	}
	out := new(CdnCors)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CdnList) DeepCopyInto(out *CdnList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Cdn, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CdnList.
func (in *CdnList) DeepCopy() *CdnList {
	if in == nil {
		return nil
	}
	out := new(CdnList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CdnList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CdnObservation) DeepCopyInto(out *CdnObservation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(int64)
		**out = **in
	}
	if in.TechnicalDomain != nil {
		in, out := &in.TechnicalDomain, &out.TechnicalDomain
		*out = new(string)
		**out = **in
	}
	if in.State != nil {
		in, out := &in.State, &out.State
		*out = new(string)
		**out = **in
	}
	if in.Source != nil {
		in, out := &in.Source, &out.Source
		*out = new(string)
		**out = **in
	}
	if in.LockedPresetID != nil {
		in, out := &in.LockedPresetID, &out.LockedPresetID
		*out = new(int64)
		**out = **in
	}
	if in.LastPurgedAt != nil {
		in, out := &in.LastPurgedAt, &out.LastPurgedAt
		*out = (*in).DeepCopy()
	}
	if in.Domains != nil {
		in, out := &in.Domains, &out.Domains
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ObservedSettings != nil {
		in, out := &in.ObservedSettings, &out.ObservedSettings
		*out = new(CdnSettingsMirror)
		(*in).DeepCopyInto(*out)
	}
	if in.TrafficUsage != nil {
		in, out := &in.TrafficUsage, &out.TrafficUsage
		*out = new(CdnTrafficUsage)
		(*in).DeepCopyInto(*out)
	}
	if in.Certificate != nil {
		in, out := &in.Certificate, &out.Certificate
		*out = new(CdnCertificateStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.ManagedCertificate != nil {
		in, out := &in.ManagedCertificate, &out.ManagedCertificate
		*out = new(CdnCertificateStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.SSL != nil {
		in, out := &in.SSL, &out.SSL
		*out = new(CdnSSLStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.TrafficLimitBytes != nil {
		in, out := &in.TrafficLimitBytes, &out.TrafficLimitBytes
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CdnObservation.
func (in *CdnObservation) DeepCopy() *CdnObservation {
	if in == nil {
		return nil
	}
	out := new(CdnObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CdnOrigin) DeepCopyInto(out *CdnOrigin) {
	*out = *in
	if in.BucketRef != nil {
		in, out := &in.BucketRef, &out.BucketRef
		*out = new(CdnBucketRef)
		**out = **in
	}
	if in.Domain != nil {
		in, out := &in.Domain, &out.Domain
		*out = new(string)
		**out = **in
	}
	if in.IP != nil {
		in, out := &in.IP, &out.IP
		*out = new(string)
		**out = **in
	}
	if in.HTTPS != nil {
		in, out := &in.HTTPS, &out.HTTPS
		*out = new(bool)
		**out = **in
	}
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(int64)
		**out = **in
	}
	if in.AWSAuthSecretRef != nil {
		in, out := &in.AWSAuthSecretRef, &out.AWSAuthSecretRef
		*out = new(CdnSecretRef)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CdnOrigin.
func (in *CdnOrigin) DeepCopy() *CdnOrigin {
	if in == nil {
		return nil
	}
	out := new(CdnOrigin)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CdnParameters) DeepCopyInto(out *CdnParameters) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.ProjectID != nil {
		in, out := &in.ProjectID, &out.ProjectID
		*out = new(int)
		**out = **in
	}
	in.Origin.DeepCopyInto(&out.Origin)
	if in.Cache != nil {
		in, out := &in.Cache, &out.Cache
		*out = new(CdnCache)
		(*in).DeepCopyInto(*out)
	}
	if in.Security != nil {
		in, out := &in.Security, &out.Security
		*out = new(CdnSecurity)
		(*in).DeepCopyInto(*out)
	}
	if in.Performance != nil {
		in, out := &in.Performance, &out.Performance
		*out = new(CdnPerformance)
		(*in).DeepCopyInto(*out)
	}
	if in.Cors != nil {
		in, out := &in.Cors, &out.Cors
		*out = new(CdnCors)
		(*in).DeepCopyInto(*out)
	}
	if in.Domains != nil {
		in, out := &in.Domains, &out.Domains
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.SSL != nil {
		in, out := &in.SSL, &out.SSL
		*out = new(CdnSSL)
		(*in).DeepCopyInto(*out)
	}
	if in.TrafficLimitGBPerMonth != nil {
		in, out := &in.TrafficLimitGBPerMonth, &out.TrafficLimitGBPerMonth
		*out = new(int64)
		**out = **in
	}
	if in.RequestHeaders != nil {
		in, out := &in.RequestHeaders, &out.RequestHeaders
		*out = make([]CdnRequestHeader, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CdnParameters.
func (in *CdnParameters) DeepCopy() *CdnParameters {
	if in == nil {
		return nil
	}
	out := new(CdnParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CdnPerformance) DeepCopyInto(out *CdnPerformance) {
	*out = *in
	if in.HTTP3 != nil {
		in, out := &in.HTTP3, &out.HTTP3
		*out = new(bool)
		**out = **in
	}
	if in.Gzip != nil {
		in, out := &in.Gzip, &out.Gzip
		*out = new(bool)
		**out = **in
	}
	if in.LargeFileSlicingMB != nil {
		in, out := &in.LargeFileSlicingMB, &out.LargeFileSlicingMB
		*out = new(int64)
		**out = **in
	}
	if in.ContentOptimization != nil {
		in, out := &in.ContentOptimization, &out.ContentOptimization
		*out = new(string)
		**out = **in
	}
	if in.Robots != nil {
		in, out := &in.Robots, &out.Robots
		*out = new(CdnRobots)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CdnPerformance.
func (in *CdnPerformance) DeepCopy() *CdnPerformance {
	if in == nil {
		return nil
	}
	out := new(CdnPerformance)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CdnRequestHeader) DeepCopyInto(out *CdnRequestHeader) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CdnRequestHeader.
func (in *CdnRequestHeader) DeepCopy() *CdnRequestHeader {
	if in == nil {
		return nil
	}
	out := new(CdnRequestHeader)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CdnRobots) DeepCopyInto(out *CdnRobots) {
	*out = *in
	if in.Custom != nil {
		in, out := &in.Custom, &out.Custom
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CdnRobots.
func (in *CdnRobots) DeepCopy() *CdnRobots {
	if in == nil {
		return nil
	}
	out := new(CdnRobots)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CdnSSL) DeepCopyInto(out *CdnSSL) {
	*out = *in
	if in.CertificateSecretRef != nil {
		in, out := &in.CertificateSecretRef, &out.CertificateSecretRef
		*out = new(CdnSecretRef)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CdnSSL.
func (in *CdnSSL) DeepCopy() *CdnSSL {
	if in == nil {
		return nil
	}
	out := new(CdnSSL)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CdnSSLStatus) DeepCopyInto(out *CdnSSLStatus) {
	*out = *in
	if in.State != nil {
		in, out := &in.State, &out.State
		*out = new(string)
		**out = **in
	}
	if in.IssueAttempts != nil {
		in, out := &in.IssueAttempts, &out.IssueAttempts
		*out = new(int64)
		**out = **in
	}
	if in.LastIssueAttemptAt != nil {
		in, out := &in.LastIssueAttemptAt, &out.LastIssueAttemptAt
		*out = (*in).DeepCopy()
	}
	if in.BudgetKey != nil {
		in, out := &in.BudgetKey, &out.BudgetKey
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CdnSSLStatus.
func (in *CdnSSLStatus) DeepCopy() *CdnSSLStatus {
	if in == nil {
		return nil
	}
	out := new(CdnSSLStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CdnSecretRef) DeepCopyInto(out *CdnSecretRef) {
	*out = *in
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CdnSecretRef.
func (in *CdnSecretRef) DeepCopy() *CdnSecretRef {
	if in == nil {
		return nil
	}
	out := new(CdnSecretRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CdnSecureToken) DeepCopyInto(out *CdnSecureToken) {
	*out = *in
	in.SecretRef.DeepCopyInto(&out.SecretRef)
	if in.RestrictByIP != nil {
		in, out := &in.RestrictByIP, &out.RestrictByIP
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CdnSecureToken.
func (in *CdnSecureToken) DeepCopy() *CdnSecureToken {
	if in == nil {
		return nil
	}
	out := new(CdnSecureToken)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CdnSecurity) DeepCopyInto(out *CdnSecurity) {
	*out = *in
	if in.ForceHTTPS != nil {
		in, out := &in.ForceHTTPS, &out.ForceHTTPS
		*out = new(bool)
		**out = **in
	}
	if in.SecureToken != nil {
		in, out := &in.SecureToken, &out.SecureToken
		*out = new(CdnSecureToken)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CdnSecurity.
func (in *CdnSecurity) DeepCopy() *CdnSecurity {
	if in == nil {
		return nil
	}
	out := new(CdnSecurity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CdnSettingsMirror) DeepCopyInto(out *CdnSettingsMirror) {
	*out = *in
	if in.Cache != nil {
		in, out := &in.Cache, &out.Cache
		*out = new(CdnCache)
		(*in).DeepCopyInto(*out)
	}
	if in.Security != nil {
		in, out := &in.Security, &out.Security
		*out = new(CdnSecurity)
		(*in).DeepCopyInto(*out)
	}
	if in.Performance != nil {
		in, out := &in.Performance, &out.Performance
		*out = new(CdnPerformance)
		(*in).DeepCopyInto(*out)
	}
	if in.Cors != nil {
		in, out := &in.Cors, &out.Cors
		*out = new(CdnCors)
		(*in).DeepCopyInto(*out)
	}
	if in.RequestHeaderNames != nil {
		in, out := &in.RequestHeaderNames, &out.RequestHeaderNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CdnSettingsMirror.
func (in *CdnSettingsMirror) DeepCopy() *CdnSettingsMirror {
	if in == nil {
		return nil
	}
	out := new(CdnSettingsMirror)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CdnSpec) DeepCopyInto(out *CdnSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CdnSpec.
func (in *CdnSpec) DeepCopy() *CdnSpec {
	if in == nil {
		return nil
	}
	out := new(CdnSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CdnStatus) DeepCopyInto(out *CdnStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CdnStatus.
func (in *CdnStatus) DeepCopy() *CdnStatus {
	if in == nil {
		return nil
	}
	out := new(CdnStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CdnTrafficUsage) DeepCopyInto(out *CdnTrafficUsage) {
	*out = *in
	if in.Requests != nil {
		in, out := &in.Requests, &out.Requests
		*out = new(int64)
		**out = **in
	}
	if in.OutgoingTrafficBytes != nil {
		in, out := &in.OutgoingTrafficBytes, &out.OutgoingTrafficBytes
		*out = new(int64)
		**out = **in
	}
	if in.CacheRatio != nil {
		in, out := &in.CacheRatio, &out.CacheRatio
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CdnTrafficUsage.
func (in *CdnTrafficUsage) DeepCopy() *CdnTrafficUsage {
	if in == nil {
		return nil
	}
	out := new(CdnTrafficUsage)
	in.DeepCopyInto(out)
	return out
}
